baseurl: "" # the subpath of your site, e.g. /blog
url: cryptoswarm.github.io # the base hostname & protocol for your site, e.g. http://example.com
title: Let's learn together
description: My space where i share courses i've taken, projects i've worked on and what i'm currently learning.
author:
  twitter: Crypto_Ar
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
